### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by thunder87** [infanion-plugins/translator-pro#1]
Unable to install the package as it's not found through **php craft plugin/install translator-pro** and composer require ip-craft/translator-pro fails with the following error.

`
Problem 1
    - ip-craft/translator-pro[1.0.0, ..., 1.0.1] require codeception/codeception ^3.0 -> satisfiable by codeception/codeception[3.0.0, ..., 3.1.3].
    - codeception/codeception[3.0.0, ..., 3.1.3] require symfony/finder >=2.7 <5.0 -> found symfony/finder[v2.7.0, ..., v2.8.52, v3.0.0, ..., v3.4.47, v4.0.0, ..., v4.4.27] but the package is fixed to v5.3.4 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - Root composer.json requires ip-craft/translator-pro ^1.0 -> satisfiable by ip-craft/translator-pro[1.0.0, 1.0.1].
`

Running the latest version of craft as of today (3.7.8) and composer v2

**Comment by Infanion-Admin** [comment]
Hey @thunder87 we have released fixes for installation issue, please check latest version 1.0.5
